let menu_services = document.getElementById("menu-services")
let menu_pricing = document.getElementById("menu-pricing")
let menu_blog = document.getElementById("menu-blog")
let navbar = document.getElementsByClassName("nav-item")
let Astronaut=document.getElementById("Astronaut")
Astronaut.addEventListener("click", () => {
    menu_services.classList.remove("menu-start")
    menu_services.classList.add("menu-stop")
    menu_pricing.classList.remove("menu-start")
    menu_pricing.classList.add("menu-stop")
    menu_blog.classList.remove("menu-start")
    menu_blog.classList.add("menu-stop")
})
navbar.item(0).addEventListener("click", () => {
    menu_services.classList.remove("menu-start")
    menu_services.classList.add("menu-stop")
    menu_pricing.classList.remove("menu-start")
    menu_pricing.classList.add("menu-stop")
    menu_blog.classList.remove("menu-start")
    menu_blog.classList.add("menu-stop")
})
navbar.item(1).addEventListener("click", () => {
    menu_services.classList.remove("menu-stop")
    menu_services.classList.add("menu-start")
    menu_pricing.classList.remove("menu-start")
    menu_pricing.classList.add("menu-stop")
    menu_blog.classList.remove("menu-start")
    menu_blog.classList.add("menu-stop")
})
navbar.item(2).addEventListener("click", () => {
    menu_services.classList.remove("menu-start")
    menu_services.classList.add("menu-stop")
    menu_pricing.classList.remove("menu-stop")
    menu_pricing.classList.add("menu-start")
    menu_blog.classList.remove("menu-start")
    menu_blog.classList.add("menu-stop")
})
navbar.item(3).addEventListener("click", () => {
    menu_services.classList.remove("menu-start")
    menu_services.classList.add("menu-stop")
    menu_pricing.classList.remove("menu-start")
    menu_pricing.classList.add("menu-stop")
    menu_blog.classList.remove("menu-stop")
    menu_blog.classList.add("menu-start")
})